# $FreeBSD$

PORTNAME=	openvpn-access-server
PORTVERSION=	2.5.2
PORTREVISION=	0
CATEGORIES=	security linux

MAINTAINER=	rainbow@sanitylinux.org
COMMENT=	OpenVPN Access Server Software (Linux CentOS ${LINUX_DIST_VER})

LICENSE=	Proprietary

RUN_DEPENDS=	python>2:lang/python

DESCR=		${.CURDIR}/../${PORTNAME}/pkg-descr
RPMVERSION=	4.el6
USES=		linux:c6
USE_LDCONFIG=	yes
USE_LINUX_RPM=	yes

.include <bsd.port.mk>
